<?php

namespace Palme\AnnaleBundle;

use Doctrine\ORM\EntityRepository;

/**
 * Entity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Entity extends EntityRepository
{
}
